apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: redis
    tier: backend
spec:
#  type: NodePort
  ports:
  - name: redis
    port: 6379
    targetPort: 6379
#    nodePort: 30379
  selector:
    app: redis
    tier: backend
---
apiVersion: v1
kind: Service
metadata:
  name: redis-prom
  labels:
    app: redis
    tier: backend
spec:
  ports:
  - name: prom
    port: 9121
    targetPort: 9121
  selector:
    app: redis
    tier: backend
