apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: cv-agent-vsa-win
  annotations:
    metric-config.external.prometheus-query.prometheus/vsa-active-workers: |
      scalar(redis_key_size{key="vsa-workers-busy"} OR on() vector(0)) + (scalar(redis_key_size{key="vsa-jobs-pending"} OR on() vector(0))/2)
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cv-agent-vsa-win
  minReplicas: 1
  maxReplicas: 5
  behavior:
    scaleDown:
      selectPolicy: Disabled
  metrics:
  - type: External
    external:
      metric:
        name: prometheus-query
        selector:
          matchLabels:
            query-name: vsa-active-workers
      target:
        type: AverageValue
        averageValue: "1"
